[2024-06-03T20:05:11.160+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T20:05:11.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-08-12T15:00:00+00:00 [queued]>
[2024-06-03T20:05:11.205+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-08-12T15:00:00+00:00 [queued]>
[2024-06-03T20:05:11.205+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-03T20:05:11.232+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2022-08-12 15:00:00+00:00
[2024-06-03T20:05:11.243+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2242) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T20:05:11.244+0000] {standard_task_runner.py:63} INFO - Started process 2301 to run task
[2024-06-03T20:05:11.266+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2022-08-12T15:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpyoora7rw']
[2024-06-03T20:05:11.267+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask pipeline
[2024-06-03T20:05:11.311+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2022-08-12T15:00:00+00:00 [running]> on host ece5ff154bbf
[2024-06-03T20:05:11.424+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2022-08-12T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-12T15:00:00+00:00'
[2024-06-03T20:05:11.425+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T20:05:13.275+0000] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2024-06-03T20:05:32.665+0000] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7767, acc_std: 0.0049
[2024-06-03T20:05:44.245+0000] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2024-06-03T20:05:44.245+0000] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2024-06-03T20:05:48.082+0000] {pipeline.py:129} INFO - Model is saved as /home/***/***_hw/data/models/cars_pipe_202406032005.pkl
[2024-06-03T20:05:48.084+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T20:05:48.084+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T20:05:48.090+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2022-08-12T15:00:00+00:00, execution_date=20220812T150000, start_date=20240603T200511, end_date=20240603T200548
[2024-06-03T20:05:48.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T20:05:48.128+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T20:05:48.130+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T20:13:04.510+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T20:13:04.525+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-08-12T15:00:00+00:00 [queued]>
[2024-06-05T20:13:04.531+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-08-12T15:00:00+00:00 [queued]>
[2024-06-05T20:13:04.531+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T20:13:04.552+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2022-08-12 15:00:00+00:00
[2024-06-05T20:13:04.563+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4004) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T20:13:04.581+0000] {standard_task_runner.py:63} INFO - Started process 4142 to run task
[2024-06-05T20:13:04.590+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2022-08-12T15:00:00+00:00', '--job-id', '1404', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpayr_hcpp']
[2024-06-05T20:13:04.590+0000] {standard_task_runner.py:91} INFO - Job 1404: Subtask pipeline
[2024-06-05T20:13:04.658+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2022-08-12T15:00:00+00:00 [running]> on host d0ff8214a49e
[2024-06-05T20:13:04.772+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2022-08-12T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-12T15:00:00+00:00'
[2024-06-05T20:13:04.773+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T20:13:04.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T20:13:04.775+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 73, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/train/homework.csv'
[2024-06-05T20:13:04.802+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2022-08-12T15:00:00+00:00, execution_date=20220812T150000, start_date=20240605T201304, end_date=20240605T201304
[2024-06-05T20:13:04.832+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1404 for task pipeline ([Errno 2] No such file or directory: './data/train/homework.csv'; 4142)
[2024-06-05T20:13:04.881+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T20:13:04.922+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T20:13:04.928+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
