[2024-06-05T17:19:41.813+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T17:19:41.845+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2024-03-25T15:00:00+00:00 [queued]>
[2024-06-05T17:19:41.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2024-03-25T15:00:00+00:00 [queued]>
[2024-06-05T17:19:41.851+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T17:19:41.868+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2024-03-25 15:00:00+00:00
[2024-06-05T17:19:41.894+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=63) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T17:19:41.895+0000] {standard_task_runner.py:63} INFO - Started process 290 to run task
[2024-06-05T17:19:41.903+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2024-03-25T15:00:00+00:00', '--job-id', '1268', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpkda4d83r']
[2024-06-05T17:19:41.904+0000] {standard_task_runner.py:91} INFO - Job 1268: Subtask pipeline
[2024-06-05T17:19:41.976+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2024-03-25T15:00:00+00:00 [running]> on host ece5ff154bbf
[2024-06-05T17:19:42.138+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T15:00:00+00:00'
[2024-06-05T17:19:42.139+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T17:19:43.749+0000] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2024-06-05T17:20:02.872+0000] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7766, acc_std: 0.0048
[2024-06-05T17:20:13.602+0000] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2024-06-05T17:20:13.602+0000] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2024-06-05T17:20:16.448+0000] {pipeline.py:129} INFO - Model is saved as /home/***/***_hw/data/models/cars_pipe_202406051720.pkl
[2024-06-05T17:20:16.452+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T17:20:16.453+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T17:20:16.459+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2024-03-25T15:00:00+00:00, execution_date=20240325T150000, start_date=20240605T171941, end_date=20240605T172016
[2024-06-05T17:20:16.523+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T17:20:16.536+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T17:20:16.538+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T21:04:18.782+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T21:04:18.806+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2024-03-25T15:00:00+00:00 [queued]>
[2024-06-05T21:04:18.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2024-03-25T15:00:00+00:00 [queued]>
[2024-06-05T21:04:18.813+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T21:04:18.822+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2024-03-25 15:00:00+00:00
[2024-06-05T21:04:18.838+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=22457) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T21:04:18.839+0000] {standard_task_runner.py:63} INFO - Started process 22639 to run task
[2024-06-05T21:04:18.842+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2024-03-25T15:00:00+00:00', '--job-id', '2592', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmphvc2_5w_']
[2024-06-05T21:04:18.842+0000] {standard_task_runner.py:91} INFO - Job 2592: Subtask pipeline
[2024-06-05T21:04:18.891+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2024-03-25T15:00:00+00:00 [running]> on host d0ff8214a49e
[2024-06-05T21:04:18.975+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T15:00:00+00:00'
[2024-06-05T21:04:18.976+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T21:04:18.978+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T21:04:18.978+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 73, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/train/homework.csv'
[2024-06-05T21:04:18.989+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2024-03-25T15:00:00+00:00, execution_date=20240325T150000, start_date=20240605T210418, end_date=20240605T210418
[2024-06-05T21:04:19.003+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2592 for task pipeline ([Errno 2] No such file or directory: './data/train/homework.csv'; 22639)
[2024-06-05T21:04:19.056+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T21:04:19.080+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T21:04:19.092+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
