[2024-06-03T20:06:01.154+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T20:06:01.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-08-22T15:00:00+00:00 [queued]>
[2024-06-03T20:06:01.188+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-08-22T15:00:00+00:00 [queued]>
[2024-06-03T20:06:01.189+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-03T20:06:01.205+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2022-08-22 15:00:00+00:00
[2024-06-03T20:06:01.217+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2391) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T20:06:01.218+0000] {standard_task_runner.py:63} INFO - Started process 2538 to run task
[2024-06-03T20:06:01.234+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2022-08-22T15:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmp0tci4sbs']
[2024-06-03T20:06:01.235+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask pipeline
[2024-06-03T20:06:01.334+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2022-08-22T15:00:00+00:00 [running]> on host ece5ff154bbf
[2024-06-03T20:06:01.486+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2022-08-22T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-22T15:00:00+00:00'
[2024-06-03T20:06:01.489+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T20:06:02.774+0000] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2024-06-03T20:06:23.598+0000] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7767, acc_std: 0.0049
[2024-06-03T20:06:36.552+0000] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2024-06-03T20:06:36.552+0000] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2024-06-03T20:06:39.052+0000] {pipeline.py:129} INFO - Model is saved as /home/***/***_hw/data/models/cars_pipe_202406032006.pkl
[2024-06-03T20:06:39.054+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T20:06:39.054+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T20:06:39.060+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2022-08-22T15:00:00+00:00, execution_date=20220822T150000, start_date=20240603T200601, end_date=20240603T200639
[2024-06-03T20:06:39.107+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T20:06:39.118+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T20:06:39.122+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T20:13:05.702+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T20:13:05.714+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-08-22T15:00:00+00:00 [queued]>
[2024-06-05T20:13:05.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-08-22T15:00:00+00:00 [queued]>
[2024-06-05T20:13:05.720+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T20:13:05.728+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2022-08-22 15:00:00+00:00
[2024-06-05T20:13:05.739+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T20:13:05.740+0000] {standard_task_runner.py:63} INFO - Started process 4222 to run task
[2024-06-05T20:13:05.740+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2022-08-22T15:00:00+00:00', '--job-id', '1413', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmp9lixq9v5']
[2024-06-05T20:13:05.740+0000] {standard_task_runner.py:91} INFO - Job 1413: Subtask pipeline
[2024-06-05T20:13:05.767+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2022-08-22T15:00:00+00:00 [running]> on host d0ff8214a49e
[2024-06-05T20:13:05.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2022-08-22T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-22T15:00:00+00:00'
[2024-06-05T20:13:05.818+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T20:13:05.819+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T20:13:05.819+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 73, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/train/homework.csv'
[2024-06-05T20:13:05.825+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2022-08-22T15:00:00+00:00, execution_date=20220822T150000, start_date=20240605T201305, end_date=20240605T201305
[2024-06-05T20:13:05.833+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1413 for task pipeline ([Errno 2] No such file or directory: './data/train/homework.csv'; 4222)
[2024-06-05T20:13:05.872+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T20:13:05.888+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T20:13:05.889+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
