[2024-06-03T18:59:29.216+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T18:59:29.239+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-07-19T15:00:00+00:00 [queued]>
[2024-06-03T18:59:29.251+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-07-19T15:00:00+00:00 [queued]>
[2024-06-03T18:59:29.252+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-03T18:59:29.269+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2022-07-19 15:00:00+00:00
[2024-06-03T18:59:29.283+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=996) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T18:59:29.286+0000] {standard_task_runner.py:63} INFO - Started process 1167 to run task
[2024-06-03T18:59:29.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2022-07-19T15:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpdqmm25nw']
[2024-06-03T18:59:29.288+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask pipeline
[2024-06-03T18:59:29.371+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2022-07-19T15:00:00+00:00 [running]> on host ece5ff154bbf
[2024-06-03T18:59:29.533+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2022-07-19T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-19T15:00:00+00:00'
[2024-06-03T18:59:29.533+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T18:59:30.853+0000] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2024-06-03T18:59:47.195+0000] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7767, acc_std: 0.0049
[2024-06-03T18:59:58.630+0000] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2024-06-03T18:59:58.630+0000] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2024-06-03T19:00:03.175+0000] {pipeline.py:129} INFO - Model is saved as /home/***/***_hw/data/models/cars_pipe_202406031900.pkl
[2024-06-03T19:00:03.178+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T19:00:03.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T19:00:03.186+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2022-07-19T15:00:00+00:00, execution_date=20220719T150000, start_date=20240603T185929, end_date=20240603T190003
[2024-06-03T19:00:03.244+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T19:00:03.255+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T19:00:03.259+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T20:10:37.722+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T20:10:37.738+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-07-19T15:00:00+00:00 [queued]>
[2024-06-05T20:10:37.746+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-07-19T15:00:00+00:00 [queued]>
[2024-06-05T20:10:37.746+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T20:10:37.755+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2022-07-19 15:00:00+00:00
[2024-06-05T20:10:37.766+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3077) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T20:10:37.767+0000] {standard_task_runner.py:63} INFO - Started process 3226 to run task
[2024-06-05T20:10:37.767+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2022-07-19T15:00:00+00:00', '--job-id', '1348', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpfcc_gnfc']
[2024-06-05T20:10:37.768+0000] {standard_task_runner.py:91} INFO - Job 1348: Subtask pipeline
[2024-06-05T20:10:37.796+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2022-07-19T15:00:00+00:00 [running]> on host d0ff8214a49e
[2024-06-05T20:10:37.855+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2022-07-19T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-19T15:00:00+00:00'
[2024-06-05T20:10:37.856+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T20:10:37.857+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T20:10:37.857+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 73, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/train/homework.csv'
[2024-06-05T20:10:37.863+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2022-07-19T15:00:00+00:00, execution_date=20220719T150000, start_date=20240605T201037, end_date=20240605T201037
[2024-06-05T20:10:37.873+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1348 for task pipeline ([Errno 2] No such file or directory: './data/train/homework.csv'; 3226)
[2024-06-05T20:10:37.900+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T20:10:37.915+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T20:10:37.917+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
